### ISSUE TITLE
Alle elementer som ikke er selv-lukkende må ha noe innhold

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nlbpub#10]
Se for eksempel: http://xahlee.info/js/html5_non-closing_tag.html

Hvis vi slipper å ta hensyn til at det kan finnes tagger uten innhold (f.eks. div og span) så er det enklere å generere riktig utputt med XSLT.

Eksempel:
Dette er ikke lov i HTML, kun i XHTML: `<p>Hei <strong/> på dere!</p>`. I HTML vil dette tolkes som `<p>Hei <strong> på dere!</strong></p>`.

**Comment by matskober** [comment]
Hvordan definerer du en "selvlukkende tag"? Er <br/> selvlukkende?

2017-12-18 17:20 GMT+00:00 Jostein Austvik Jacobsen <
notifications@github.com>:

**Comment by josteinaj** [comment]
Ja, br er selvlukkende. Også img, meta og hr. Selvlukkende tagger er en XML-greie. I vanlig HTML (ikke XHTML) så betyr skråstrek på slutten av taggen ingenting, det avhenger kun av tagg-navnet. Altså kan ikke br, hr osv ha sluttagg, og div, span, p, etc må alltid ha sluttagg.

**Comment by olavindergaard** [comment]
👍

**Comment by olavindergaard** [comment]
Det er vel disse som er valide selvlukkende elementer i HTML5:
`- <area /><base /><br /><col /><command /><embed /><hr /><img /><input /><link /><meta /><param /><source /><track /><wbr />`

Vi kan se bort fra `<keygen />` tror jeg.
