### ISSUE TITLE
Tusenskilletegn og andre skilletegn i tall

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nlbpub#8]
Kan vi validere tall? Det skaper for eksempel problemer i punktskrift når et tall har mellomrom i seg: https://github.com/nlbdev/pipeline/issues/12

**Comment by olavindergaard** [comment]
Dette er et minefelt...hvilke skilletegn er problematiske? Akkuart mellomrom er vel ikke så problematisk å fjerne (men mange av uttalereglene i TTS baserer seg på skilletegn (feks for et telefonnummer så vil dette slå uheldig ut for TTS)...

I noen tilfeller må vi også ta høyde for at det skal være whitespace mellom tall og skilletegn (feks ratio) eksempel: Målestokken er 1 : 100

**Comment by josteinaj** [comment]
Sant nok. Men hva med en enkel regel som f.eks. at to tall ikke kan adskilles av kun mellomrom? Og hvis man ønsker mellomrom så må man enten bruke `&nbsp;` eller en eller annen CSS-metode?

**Comment by olavindergaard** [comment]
Jeg ser ingen problemer der. Mellomrom i tall er en vederstyggelihhet uansett! Vi deskvalifiserer alle tall med mellomrom som invalide.

**Comment by olavindergaard** [comment]
Det høres fornuftig ut. Vi går for den 👍

**Comment by josteinaj** [comment]
Også legge til advarsler i en HTML-rapport for manuell gjennomgang ved mottakskontroll.

**Comment by josteinaj** [comment]
Erstattet av: https://github.com/nlbdev/epub3-guidelines-update/issues/77
